### NumPy

#### array()

In [2]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


#### shape() & dtype()

In [4]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [5]:
lst=[1.2,2.5,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [7]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


#### Re-Shape the Given Array
#### numpy.reshape(arrayName,reshape,order='C')

In [14]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
A = np.ones((4,3,4,3),dtype=np.int64)
print(A)

[[[[1 1 1]
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   [1 1 1]]]]


In [16]:
A = np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [17]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [1]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [3]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [5]:
#Indexing & Slicing of Numpy
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [18]:
a1=np.array([(1,2,3),(4,5,6)])
print("Second Row: ",a1[1,2])

Second Row:  6


In [7]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing Column:",a1[:,1])

Slicing Column: [2 5]


In [9]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing Last Column:",a1[:,2])

Slicing Last Column: [3 6]


In [19]:
a1=np.array([(1,2,3),(4,5,6)])
print("Row & Column:",a1[:])

Row & Column: [[1 2 3]
 [4 5 6]]


### Some math Operations on the given Random No
#### Min        -- returns the least no
#### Max       -- return the largest no
#### Mean     -- Mean
#### Median  -- Median
#### GD         -- Gaussian Distribution

In [13]:
a1=np.random.normal(5,1,10)
print(a1)
print("Min Value =",np.min(a1))
print("Max Value =",np.max(a1))
print("Mean Value =",np.mean(a1))
print("Median Value =",np.median(a1))

[5.43294322 3.94664648 4.88687217 4.97642639 3.39008207 4.99782976
 3.96937384 7.3587513  4.57949342 3.18832735]
Min Value = 3.1883273523960893
Max Value = 7.3587512970381095
Mean Value = 4.672674600144796
Median Value = 4.733182798338527


#### Multiply 1D Array
#### numpy.dot (x,y)

In [14]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [20]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [21]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])